### ISSUE TITLE
Automating refreshing views

### ISSUE THREAD

**Issue by chreex** [qgears/qgears-review-tool#14]
If a new review is created for a file, the following view updates should be performed without user interaction: 
* removing the file from the review-related 'Todo list' if status is set to OK by the user
* icon in the review tool main view

**Comment by agostoni** [comment]
The status panel of the 'Todo list view' also should be refreshed automatically.

Currently the review model does not provide model change events, so it is unknown when must be the viewers and other GUI elements updated. We should implement this event, and hook updates on it.
